name: Keep Render Backends Warm

on:
  schedule:
    # Every 10 minutes (UTC)
    - cron: "*/10 * * * *"
  workflow_dispatch: {}  # allows manual trigger

permissions:
  contents: read
  actions: write

jobs:
  warm:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Pick random User-Agents for each request
        id: ua
        run: |
          UAS=(
            "Mozilla/5.0 (Windows NT 10.0; Win64; x64)"
            "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)"
            "Mozilla/5.0 (X11; Linux x86_64)"
            "Mozilla/5.0 (iPhone; CPU iPhone OS 15_0 like Mac OS X)"
            "Mozilla/5.0 (iPad; CPU OS 15_0 like Mac OS X)"
            "Mozilla/5.0 (Android 10; Mobile; rv:79.0) Gecko/79.0 Firefox/79.0"
            "Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko"
          )
          UA_A=${UAS[$RANDOM % ${#UAS[@]}]}
          UA_B=${UAS[$RANDOM % ${#UAS[@]}]}
          echo "ua_a=$UA_A" >> "$GITHUB_OUTPUT"
          echo "ua_b=$UA_B" >> "$GITHUB_OUTPUT"

      - name: Random jitter (0–59s) to avoid obvious patterns
        run: sleep $((RANDOM % 60))

      - name: Ping both apps in parallel
        continue-on-error: true
        run: |
          set -euxo pipefail
          (
            echo -n "App A status: "
            curl -sS -o /dev/null -w "%{http_code}\n" \
              -A "${{ steps.ua.outputs.ua_a }}" \
              -H "Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8" \
              -H "Accept-Language: en-US,en;q=0.9" \
              -H "Connection: keep-alive" \
              -H "Referer: https://google.com" \
              --retry 3 --retry-delay 2 --retry-all-errors --max-time 60 \
              "https://iit-bhilai-student-forum.onrender.com/warmup/"
          ) &
          (
            echo -n "App B status: "
            curl -sS -o /dev/null -w "%{http_code}\n" \
              -A "${{ steps.ua.outputs.ua_b }}" \
              -H "Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8" \
              -H "Accept-Language: en-US,en;q=0.9" \
              -H "Connection: keep-alive" \
              -H "Referer: https://google.com" \
              --retry 3 --retry-delay 2 --retry-all-errors --max-time 60 \
              "https://timetable-creator-n51f.onrender.com/get_all_courses/"
          ) &
          wait
